name: Extract domains
on:
  schedule:
    - cron: '0 3 * * 1'
  workflow_dispatch:
permissions:
  contents: write
jobs:
  extract:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download and extract
        run: |
          wget -qO dlc.yml https://github.com/v2fly/domain-list-community/releases/latest/download/dlc.dat_plain.yml
          mkdir -p lists/
          python3 extract.py
      - name: Commit
        run: |
          git config user.email "bot@bot"
          git config user.name "bot"
          git add lists/
          git commit -m "Update lists" && git push || true
